spring:  
#  sql:
#    init:
#      platform: h2
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant
    username: root
    password: 12345678
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
server:
  servlet:
    session:
      cookie:
        http-only: true
        secure: true