INSERT INTO Status (Status_ID, Status_Code) VALUES ('1','New Order');
INSERT INTO Status (Status_ID, Status_Code) VALUES ('2','Cooking');
INSERT INTO Status (Status_ID, Status_Code) VALUES ('3','Ready');
INSERT INTO Status (Status_ID, Status_Code) VALUES ('4','Served');
INSERT INTO Menu (Name, Price, Image_Path) VALUES ('Asiago Chicken Pasta','12.99','/chicken_pasta');
INSERT INTO Menu (Name, Price, Image_Path) VALUES ('Argentinean-Style Steak','18.99','/argentinean_steak');
INSERT INTO Menu (Name, Price, Image_Path) VALUES ('All-American Burgers','11.99','/american_burger');
INSERT INTO Menu (Name, Price, Image_Path) VALUES ('Shrimp Scampi','16.99','/shrimp_scampi');
INSERT INTO Menu (Name, Price, Image_Path) VALUES ('Chicken Fajitas','14.99','/chicken_fajita');
INSERT INTO Menu (Name, Price, Image_Path) VALUES ('Grilled Salmon','13.99','/grilled_salmon');
INSERT INTO Ticket (Ticket_Name) VALUES ('testing');
INSERT INTO Orders (Order_ID, Menu_ID, Status_ID, Ticket_ID, Notes) VALUES ('1','1','1','1','testing');